spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mini_pos_db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


file:
  server-path: /Users/macbookpro/Pictures/photo/
  client-path: /files/**
  base-url: http://localhost:8080/files/
  download-url: http://localhost:8080/api/v1/files/download/


